### ISSUE TITLE
dot notation?

### ISSUE THREAD

**Issue by MatthewMueller** [dominicbarnes/square#1]
First of all, this library is pretty freakin' sweet. Been looking for a good way to represent JSON as a flattened object, this is the closest I've seen to getting it right.

I was wondering if you're interested in supporting dot notation? Kinda ruins the name, but it'd be nice to handle that here. Here's a modified example from the Readme:

```js
square.set(o, "contacts[].first", "test1");
// => {
//   user: {
//     name: "testuser",
//     password: "123456"
//   },
//   tags: [
//     "a", "b"
//   ],
//   contacts: [
//     { first: "test1" }
//   ]
// }

square.set(o, "contacts[].last", "test2");
// => {
//   user: {
//     name: "testuser",
//     password: "123456"
//   },
//   tags: [
//     "a", "b"
//   ],
//   contacts: [
//     { first: "test1", last: "test2" }
//   ]
// }

square.set(o, "contacts[].first", "test3");
// => {
//   user: {
//     name: "testuser",
//     password: "123456"
//   },
//   tags: [
//     "a", "b"
//   ],
//   contacts: [
//     { first: "test1", last: "test2" },
//     { first: "test3" }
//   ]
// }

square.set(o, "contacts[].last", "test4");
// => {
//   user: {
//     name: "testuser",
//     password: "123456"
//   },
//   tags: [
//     "a", "b"
//   ],
//   contacts: [
//     { first: "test1", last: "test2" },
//     { first: "test3", last: "test4" }
//   ]
// }
```

**Comment by dominicbarnes** [comment]
Actually, I'm on the fence about whether or not to support this.

Not too long ago, I came across this [spec](http://www.w3.org/TR/html-json-forms/) that I think I want to move towards supporting fully. (if it doesn't already)

Is there any particular reason you'd want to mix bracket and dot notation?

**Comment by MatthewMueller** [comment]
Ah interesting, thanks for the link. Yah, probably makes more sense to just follow that spec. Dot notation is nice just because it's more familiar.

**Comment by dominicbarnes** [comment]
I don't think it's an "official" spec, afaik there is no browser support yet. Maybe we can hide dot notation support behind an optional flag? (until we start seeing browser support, in case the spec changes over time?)

**Comment by dominicbarnes** [comment]
It was trivial to just add limited dot notation support, so I went ahead and did it. Depending on how that spec and browser support goes, this could change in the future.

**Comment by matthewmueller** [comment]
> Afaik there is no browser support yet

Haha, yah... I'm not holding my breath. 

> It was trivial to just add limited dot notation support

Ahh sweet, one line change.

>  this could change in the future.

Yep, sounds good. thanks!
